services:
  mysql:
    image: mysql:8.0
    container_name: excel-to-db-mysql-test
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: test_people
    ports:
      - "3308:3306"
    volumes:
      - mysql_test_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest_password"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:14
    container_name: excel-to-db-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_people
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_test_data:
  postgres_test_data: 