services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: excel-to-db-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: people
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "mysql", "-p password"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: excel-to-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: people
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Adminer for database management (optional)
  adminer:
    image: adminer:latest
    container_name: excel-to-db-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: mysql

volumes:
  mysql_data_volume:
  postgres_data_volume: 